### ISSUE TITLE
Add Unit Testing

### ISSUE THREAD

**Issue by Guuzzeji** [Guuzzeji/youtube-scissors-cli#16]
## Notes (Really testing the timestamp generation algorithm)
Use jest.js (https://jestjs.io/docs/getting-started)

## Tasks
- [x] Have a database of YouTube videos to use, all with different types of ways to get timestamp data
~- [ ] Also have a database of local copy time stamps for descriptions and comments (this will be text data)~
~- [ ] Test and make sure FFmpeg is working currently~
- [x] Make sure each fetch YouTube Data function is working currently
- [x] Add documentation to explain how to use unit testing.
- [x] Spell check docs addon
- [x] (optional) Add GitHub action to it

**Comment by Guuzzeji** [comment]
## Helpful Notes
- https://stackoverflow.com/questions/71972012/github-actions-jest
