### ISSUE TITLE
Add GitHub action Build script

### ISSUE THREAD

**Issue by Guuzzeji** [Guuzzeji/youtube-scissors-cli#9]
# Todo
- [x] Create publish.yml
- [x] Create build script
- [x] Push build into release

# Resources
- https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/How-to-publish-GitHub-Actions-artifacts-example
- https://github.com/marketplace/actions/action-zip
- https://github.com/nektos/act
- https://github.com/msusdev/end-to-end-github-actions/blob/main/presentations/ci_github_actions.md
- https://futurestud.io/tutorials/github-actions-run-a-workflow-when-creating-a-tag
- https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags
- https://github.com/nodematiclabs/nodematic.com/blob/main/.github/workflows/release.yml
- https://github.com/marvinpinto/action-automatic-releases
- https://github.com/marketplace/actions/release-changelog-builder
